ALTER TABLE funcionario
    MODIFY COLUMN cep VARCHAR(20) NULL,
    MODIFY COLUMN logradouro VARCHAR(255) NULL,
    MODIFY COLUMN bairro VARCHAR(100) NULL,
    MODIFY COLUMN cidade VARCHAR(100) NULL,
    MODIFY COLUMN uf VARCHAR(5) NULL;